[profile.default]
src = "src"
out = "out"
test = "test"
libs = ["lib"]
optimizer = true
optimizer_runs = 200
fs_permissions = []

[rpc_endpoints]
arc = "https://rpc.drpc.mainnet.arc.io"
arc_blockdaemon = "https://rpc.blockdaemon.mainnet.arc.io"

[fmt]
line_length = 110
tab_width = 4
